name: dykal
description: DyKal - Aplikasi Private untuk Kamu & Dia. Chat, Album, Surat, Home & Call.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # --- Firebase (Tanpa Storage) ---
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.10
  firebase_app_check: ^0.2.1+6

  # --- Cloudinary (Ganti Firebase Storage, NO CC) ---
  cloudinary_public: ^0.21.0
  dio: ^5.4.0
  http: ^1.1.2
  http_parser: ^4.0.2
  mime: ^1.0.4

  # --- Realtime & State ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # --- Call Audio/Video WebRTC ---
  flutter_webrtc: ^1.0.0 # upgrade: 0.9.48 pakai v1 embedding (Registrar) yang dihapus di Flutter 3.29+; 1.x sudah fix
  # Untuk filter/efek video: GPUImage / Banuba bisa ditambah nanti
  # Untuk screen share: flutter_webrtc sudah support getDisplayMedia

  # --- Voice Note ---
  record: ^6.1.1
  just_audio: ^0.10.4
  audio_waveforms: ^1.3.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.1

  # --- UI Modern Seamless ---
  google_fonts: ^6.1.0 # Poppins & Plus Jakarta Sans
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_displaymode: ^0.6.0 # Support 60/90/120Hz
  animations: ^2.0.10

  # --- Utils ---
  intl: ^0.19.0
  uuid: ^4.2.1
  timeago: ^3.6.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0 # Compress ke WebP otomatis
  shared_preferences: ^2.2.2 # simpan preferensi tema (dark/light)
  connectivity_plus: ^6.0.5 # cek koneksi (popup no internet saat kirim)
  flutter_local_notifications: ^19.5.0 # Notif ultah (fix #2329 build error, mulai 17.2.1)
  timezone: ^0.10.1 # (dinaikkan: dibutuhkan flutter_local_notifications ^19.5.0)
  swipe_to: ^1.0.2 # Swipe to reply
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/illustrations/webp/
    - assets/logo/
    - assets/logo/webp/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/dykal_launcher.png"
  min_sdk_android: 21
